### ISSUE TITLE
Pipeline requires at least 10 CPUs

### ISSUE THREAD

**Issue by ute-hoffmann** [MPUSP/nf-core-crispriscreen#10]
Pipeline does currently not run on machines with less than 10 CPUs, since bowtie2-build and bowtie2 align seem to be configured in a way that they need at least 10 CPUs. (Error cause:  Process requirement exceeds available CPUs -- req: 10; avail: 8)

**Comment by ute-hoffmann** [comment]
Detailed output regarding error: 

> Error executing process > 'NFCORE_CRISPRISCREEN:CRISPRISCREEN:BOWTIE2_BUILD (library.fasta)'
> 
> Caused by:
>   Process requirement exceeds available CPUs -- req: 10; avail: 8
> 
> Command executed:
> 
>   mkdir bowtie2
>   bowtie2-build  --threads 10 library.fasta bowtie2/library
>   cat <<-END_VERSIONS > versions.yml
>   "NFCORE_CRISPRISCREEN:CRISPRISCREEN:BOWTIE2_BUILD":
>       bowtie2: $(echo $(bowtie2 --version 2>&1) | sed 's/^.*bowtie2-align-s version //; s/ .*$//')
>   END_VERSIONS
> 
> Command exit status:
>   -
> 
> Command output:
>   (empty)
>

**Comment by m-jahn** [comment]
The resources of the current machine can be allocated in the `nextflow.config` file, this one: https://github.com/m-jahn/nf-core-crispriscreen/blob/master/nextflow.config

On line 81:
```
    // Max resource options
    // Defaults only, expecting to be overwritten
    max_memory                 = '20.GB'
    max_cpus                   = 10
    max_time                   = '1.h'
```

**Comment by m-jahn** [comment]
Issue seems resolved.
