### ISSUE TITLE
Link in documentation broken 

### ISSUE THREAD

**Issue by ute-hoffmann** [MPUSP/nf-core-crispriscreen#11]
Link to example sample sheet in documentation is broken (https://m-jahn.github.io/nf-core-crispriscreen/usage -> "An [example samplesheet](https://m-jahn.github.io/assets/samplesheet.csv) has been provided with the pipeline." -> links to https://m-jahn.github.io/assets/samplesheet.csv)

**Comment by ute-hoffmann** [comment]
Also the following link is broken: https://github.com/nf-core/crispriscreen/releases (First, go to the [nf-core/crispriscreen releases page](https://github.com/nf-core/crispriscreen/releases) and find the latest version number - numeric only (eg. 1.3.1). Then specify this when running the pipeline with -r (one hyphen) - eg. -r 1.3.1.)

**Comment by m-jahn** [comment]
Yes, these links are written by default from the nf-core template. They don't work until the pipeline is integrated into the nf-core organization on github. In other words these are placeholders.

**Comment by m-jahn** [comment]
Issue can not be resolved right now.
