### ISSUE TITLE
MAPQ filtering after bowtie2 alignment

### ISSUE THREAD

**Issue by ute-hoffmann** [MPUSP/nf-core-crispriscreen#16]
### Description of feature

If reads are mapping ambiguously, bowtie2 assigns a MAPQ of 0 or 1 to them (compare http://biofinysics.blogspot.com/2014/05/how-does-bowtie2-assign-mapq-scores.html). I would suggest to remove those reads from .bam files after mapping. 
An easy implementation would be to force "sort_bam = false" for BOWTIE2_ALIGN (nextflow.config, line 48) and introduce "ext.args2 = '-q 1'" in conf/modules.config (line 73). If the latter is introduced and sort_bam = true, the module most likely throws an error because samtools sort does not understand "-q 1".

**Comment by m-jahn** [comment]
Very interesting link, thanks! It would be good to implement this as an optional feature for the bowtie2 module. After all, even multimapping reads are counted only once, for the best mapping reference, so users might still want to keep those.
