### ISSUE TITLE
PCAs of samples? More QC measures?

### ISSUE THREAD

**Issue by ute-hoffmann** [MPUSP/nf-core-crispriscreen#18]
### Description of feature

Li et al., 2015 (https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0843-6/tables/1) suggest QC measures for CRISPR analyses - compare Table 1. For instance, PCAs provide a good way to check if different samples correlate well / can unveil if samples were labelled wrongly in the meta data sheet. 
Maybe it might be worth it implementing some of their QC measures into the pipeline.

**Comment by ute-hoffmann** [comment]
I think it should be fairly easy to implement PCAs & a heat map into calculate_fitness.R, I can provide code for both functions that work on DESeq2 data sets.

**Comment by m-jahn** [comment]
You are welcome to make a commit and PR if you like!

**Comment by m-jahn** [comment]
Added a lot of extra QC plots with commit 13e5ed3
