### ISSUE TITLE
Mageck failing on big data sets

### ISSUE THREAD

**Issue by ute-hoffmann** [MPUSP/nf-core-crispriscreen#22]
### Description of the bug

When running the pipeline with 96 input files, the Mageck tool runs into the maximum allowed time (8.h in this case). Possibly, this might be less the case if there is less to calculate for Mageck, e.g. by taking out the "time" column out of the design matrix which is automatically generated for Mageck, or even also the "common", although this probably gives valuable information.
Alternatively, I would suggest to add a parameter to turn off Mageck calculations during pipeline execution, since this tool is not too crucial anyways?

### Command used and terminal output

```console
Error executing process > 'NFCORE_CRISPRISCREEN:CRISPRISCREEN:MAGECK_MLE (all_counts)'

 

Caused by:

  Process exceeded running time limit (8h)

 

Command executed:

 

  mageck \

      mle \

       \

      --threads 6 \

      -k all_counts.tsv \

      -d design.tsv \

      -n all_counts

  

  cat <<-END_VERSIONS > versions.yml

  "NFCORE_CRISPRISCREEN:CRISPRISCREEN:MAGECK_MLE":

      mageck: $(mageck -v)

  END_VERSIONS
```

**Comment by m-jahn** [comment]
Quite interesting! I never tested Mageck with that many input files. But I noticed too that fitness calculation takes much longer than with DESeq. I wonder if others noticed too that it takes that long. And with a lot of resources too; I usually run it with as many cores as possible, still takes much longer than DESeq with 1 core.
Might be something for the original developers of the Mageck module @LaurenceKuhl over at nf-core modules.

**Comment by LaurenceKuhl** [comment]
Hi @ute-hoffmann ,

i had a similar issue, I think i had 70 comparisons to do and it also ran out, I did a bit of nextflow magic (aka played with the channels) to get all of these comparisons to run parallelised, let me know if you're interested we could have a look, since everything is still under construction.
Thanks for tagging me Michael :)
Best,
Laurence

**Comment by m-jahn** [comment]
Hi Laurence,
Thanks for picking this conversation up :-) I wasn't sure if this works, but one can always try.
I would be very interested to learn how you achieved a better performance within an NF pipeline. From what I can see the Mageck module uses all assigned CPUs but maybe not efficiently..?

**Comment by ute-hoffmann** [comment]
Hi @LaurenceKuhl ,
for now we are fine with running the whole pipeline with DESeq2 instead of the Mageck analysis, but I think in future it could be nice to adjust this accordingly - so as @m-jahn I would actually be curious to learn about more efficient ways of including Mageck into the pipeline :) 
Cheers,
Ute
